### ISSUE TITLE
Missing oauth_signature in signed_url?

### ISSUE THREAD

**Issue by manfai777** [jrconlin/oauthsimple#27]
Hi,

There seems to be an issue with the lines below in OAuthSimple.php.  If $this->_normailzedParameters() is not used, oauth_signature would fail to be appended to signed_url which would cause a 401 error (MissingRequiredField), can this be fixed?

Anthony

public function sign($args=array())
    {
      ...
      ...
        return Array (
            'parameters' => $this->_parameters,
            'signature' => self::_oauthEscape($this->_parameters['oauth_signature']),
            //'signed_url' => $this->_path . '?' . $normParams,
            'signed_url' => $this->_path . '?' . $this->_normalizedParameters(),
            'header' => $this->getHeaderString(),
            'sbs'=> $this->sbs
            );
    }

**Comment by jrconlin** [comment]
let me know if that resolves the issue.

**Comment by manfai777** [comment]
Thanks for the fix and the unit test.  It works fine now! Just curious with oauth_signature missing before from signed_url and nobody reported this?  Looking more closely at the code, it appears that the previous bug only affects signed_url as it uses $norm_param but getHeaderString goes through all parameters including the newly added oauth_signature.  So with previous build, signed_url and headerstring are actually different.  Maybe people were using header string and not signed_url like we do?  Anyhow, thanks for all the help :)

**Comment by jrconlin** [comment]
Yeah, I think most folk were using the header string. My own damn fault for
not building out the tests before getting patches.

**Comment by manfai777** [comment]
Just want to see when a formal release will be pushed to the main branch so we can direct our users to use the updated php library.

**Comment by jrconlin** [comment]
On 3/20/2015 9:34 AM, manfai777 wrote:
>
> Just want to see when a formal release will be pushed to the main 
> branch so we can direct our users to use the updated php library.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jrconlin/oauthsimple/issues/27#issuecomment-84063099>.
>
Oh, crap! Sorry, I'm used to working in the dev branch on a bunch of 
other projects.

Merged.

**Comment by manfai777** [comment]
Thanks, when can I expect to see OAuthSimple.php updated in the master branch?

**Comment by jrconlin** [comment]
merged

**Comment by manfai777** [comment]
It appears that the signature missing issue is also apparent in the python
version of the oauthsimple library.  Can we have a similar fix deployed to
the main branch as well?

Anthony
