### ISSUE TITLE
Perl oauth_signature not generated if normalized not used

### ISSUE THREAD

**Issue by Dolnor** [jrconlin/oauthsimple#29]
Hello,
It seems like the issue #27 is affecting the perl version as well. 
Not using $this->_normalizedParameters() results in no oauth_signature on the actual signed_url .. 
I've tied playing around with the code, but since my perl is pretty poor I always end up with response saying the genned signature is invalid. Could you perhaps address this in perl code as well?

Thank you in advance.

**Comment by jrconlin** [comment]
closed via commit 4c54cc5

Which is a delightfully patterned commit id.
