### ISSUE TITLE
Composer package for PHP version of OAuthSimple

### ISSUE THREAD

**Issue by DaveBagler** [jrconlin/oauthsimple#30]
I was just wondering if you have any plans to create a composer package for the PHP version of your API?  If not, do you mind if I create a composer package for the PHP version of your API?

**Comment by jrconlin** [comment]
I wasn't planning on it, since I haven't messed with PHP in half a decade.
I gratefully bow to your expertize.

**Comment by DaveBagler** [comment]
Here's the link to the composer package: https://packagist.org/packages/baglerit/oauthsimple
Here's the github repo: https://github.com/BaglerIT/OAuthSimple

I updated the PHP by refactoring the exception into it's own file, placing both classes in a PSR-4 compliant namespace and updated the code to by PSR-2 compliant.

**Comment by jrconlin** [comment]
Cool! I'm a bit swamped with my day job, but there's an outstanding
issue with oauth_signature not being generated if normalize() isn't used
in the perl version. When I get time, i'm going to investigate that, but
I'll merge your code and update the README. (Feel free to send a PR if
you'd prefer.)

**Comment by DaveBagler** [comment]
I'll test my updates this weekend and then make a pull request hopefully next week.

I'll just fork your repo and update the class rather than pulling in all the composer stuff since it wont work/wouldn't be needed in the current multi-language format of your repo.  For composer users you can just point them to the packagist.org link.  I'll watch this repo and if you make PHP changes I'll try to update the package in a timely fashion.
