### ISSUE TITLE
Signature is not URL encoded in PHP

### ISSUE THREAD

**Issue by ottowayne** [jrconlin/oauthsimple#34]
OAuth signatures are not URL encoded in PHP and thus may result in invalid signatures depending on the contents (had me wondering why it failed seemingly random for me).

Fixed it for me by using PHPs own urlencode in the _normalizedParameters function
`$sig = urlencode($this->_generateSignature($presig));`

**Comment by infinitelyrandom** [comment]
This explains the random failures I was getting, can confirm the suggested fix worked for me.

**Comment by ottowayne** [comment]
Thanks @jrconlin
Was about to create a pull request when the comment notification reminded me of this issue :ok_hand:

**Comment by jrconlin** [comment]
no worries. sorry for the late response, but the day job has been eating a lot of my time.
